[versions]
agp = "8.11.2"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
pagingVersion = "3.2.1"
navigationFragmentKtx = "2.9.5"
navigationUiKtx = "2.9.5"
retrofit = "3.0.0"
moshiVersion = "1.15.2"
lifecycleKtx = "2.8.7"
cardviewVersion = "1.0.0"
coilVersion = "2.7.0"
swiperefreshlayout = "1.1.0"
rootVersion = "2.8.3"
ksp = "2.0.21-1.0.27"
windowVersion = "1.2.0"

[libraries]
androidx-window = { module = "androidx.window:window", version.ref = "windowVersion" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
io-coil-kt = { module = "io.coil-kt:coil", version.ref = "coilVersion"}
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardviewVersion"}
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleKtx"}
moshiConverter = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshiVersion" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshiVersion" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
paging = { group = "androidx.paging", name = "paging-runtime", version.ref = "pagingVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "rootVersion"}
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "rootVersion" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "rootVersion" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "rootVersion"}

[plugins]
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationFragmentKtx" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

